<?xml version="1.0" encoding="UTF-8"?>
<SoLIMProject Version="2010" Name="lab1" ProjectType="RBI" DataType="3dr">
 <Database>
 </Database>
 <KnowledgeBase><KnowledgeBaseFile>KnowledgeBase.xml</KnowledgeBaseFile>
 </KnowledgeBase>
 <Inference>
  <UseMask>false</UseMask>
  <Mask></Mask>
  <MaskValue>0.000000</MaskValue>
  <Directory></Directory>
  <CreateCheckFile>false</CreateCheckFile>
  </Inference>
 </SoLIMProject>
